cadastro/urls.py
from django.urls import path
from . import views


app_name = 'cadastro'
urlpatterns = [
    path('', views.inicio, name='inicio' ),
    path('cadastro/', views.cadastro, name='cadastro')
]

home/urls.py
from django.urls import path
from . import views


app_name = 'feed'
urlpatterns = [
    path('', views.pag_inicial, name='pag_inicial' ),

]

projeto_parceiros/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cadastro.urls')),
]

home/models.py
from django.db import models

# Create your models here.

cadastro/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User


# Create your views here.
def inicio(request):
   return render(request,'inicio.html')

def cadastro(request):
    if request.method == 'POST':

        email  = request.POST.get('email')
        senha = request.POST.get('senha')
        senha_confirmar = request.POST.get('confirmar_senha')
        
        usuario  =  User.objects.filter(email=email).first()
        if usuario:
            pass # retorno um json response informando que o email já está cadastrad
    
        if confirmar_senha(senha, senha_confirmar): #se passar, eu confirmo a senha
            usuario = User.objects.create_user(username=email, password=senha)
            usuario.save()
            return redirect('cadastro:inicio')
            
    else:
        return render(request,'cadastro.html')
    

def confirmar_senha (senha1, senha2):
    if senha1==senha2:
        return True
    return False

home/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required




@login_required(login_url='cadastro:inicio')
def pag_inicial(request):
    return render(request,'pag_inicial.html')

cadastro/templates/cadastro.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'cadastro/cadastro.css' %}">
    <title>Cadastro - Se liga</title>
</head>
<body>
    <div class="img_logo"><img src="{% static 'comuns/logo.png'  %}" alt="">
    </div>

    <form action="{%url 'cadastro:cadastro' %}" method="POST" >
        {% csrf_token %}
        <input type="email" name="email" placeholder="Email">
        <input type="text" placeholder="Nome Completo">
        <input type="password" id="senha" placeholder="Senha" name="senha" required >
        <div id="requisitos">
            <ul>
              <li id="requisito1">Pelo menos 8 caracteres</li>
              <li id="requisito2">Pelo menos 1 letra maiúscula</li>
              <li id="requisito3">Pelo menos 1 número</li>
              <li id="requisito4">Pelo menos 1 caractere especial</li>
            </ul>
          </div>
        <input required type="password" placeholder="Confirme sua senha" name="confirmar_senha">
        <input type="submit"  value="Cadastrar">
    </form>

  <script src="{% static 'cadastro/cadastro.js' %}" ></script>
</body>
</html>

cadastro/templates/inicio.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'cadastro/inicio.css' %}">
    <title>Inicio</title>
</head>
<body>
    <div class="img_logo"><img src="{% static 'comuns/logo.png'  %}" alt="">
    </div>

    <form action="">
        <input type="email" name="Email" placeholder="Email">
        <input type="password"  placeholder="Senha" name="senha" >
        <input type="submit" placeholder="Senha" value="Login">
    </form>
    
    <a href="{% url 'cadastro:cadastro' %}">Não possuo cadastro.</a>
</body>
</html>

home/templates/pag_inicial.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    TESTE
</body>
</html>